# Generated by Django 5.0.1 on 2024-01-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirestapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DistinoInicial',
            new_name='Destinoinicial',
        ),
        migrations.RenameField(
            model_name='asignacionenvio',
            old_name='idAsignacion',
            new_name='idasignacion',
        ),
        migrations.RenameField(
            model_name='cuentas',
            old_name='idCuenta',
            new_name='idcuenta',
        ),
        migrations.RenameField(
            model_name='destinos',
            old_name='nroPostal',
            new_name='nropostal',
        ),
        migrations.RenameField(
            model_name='nroseguimiento',
            old_name='fkFinal',
            new_name='fkfinal',
        ),
        migrations.RenameField(
            model_name='nroseguimiento',
            old_name='fkInicial',
            new_name='fkinicial',
        ),
        migrations.RenameField(
            model_name='nroseguimiento',
            old_name='idSeguimiento',
            new_name='idseguimiento',
        ),
        migrations.RenameField(
            model_name='saveseguimientos',
            old_name='idSave',
            new_name='idsave',
        ),
        migrations.RenameField(
            model_name='sesiones',
            old_name='fechaInicio',
            new_name='fechainicio',
        ),
        migrations.RenameField(
            model_name='sesiones',
            old_name='idSesion',
            new_name='idsesion',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='idCreador',
            new_name='idcreador',
        ),
    ]
