# Generated by Django 5.0.1 on 2024-01-19 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirestapp', '0002_rename_distinoinicial_destinoinicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nroseguimiento',
            name='fkinicial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirestapp.destinoinicial'),
        ),
    ]
