# Generated by Django 5.0.1 on 2024-01-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirestapp', '0003_alter_nroseguimiento_fkinicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariofinal',
            name='fkdestinofinal',
        ),
        migrations.AddField(
            model_name='cuentas',
            name='contrasenaantigua',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='destinofinal',
            name='extra',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='destinos',
            name='nropostal',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='resistencia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='temperatura',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='volumen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usuariofinal',
            name='apellido',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usuariofinal',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Apellido',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Genero',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='Nacimiento',
            field=models.DateField(blank=True),
        ),
    ]
